FROM python:3.9

# intar dependencias
RUN pip install pandas

# path en el que se trabaja la copia siguiente
WORKDIR /the/workdir/path
# script que queresmos copiar y el nombre que le damos en el docker 
COPY pipelines.py pipelines_copy.py

# lo que quiero es que cuando al lanzar el docker es que realiza un python pipelines_copy.py
ENTRYPOINT ["python","pipelines_copy.py","1"]

